### ISSUE TITLE
Variable naming

### ISSUE THREAD

**Issue by jneuendorf** [jub3i/csv2sql#1]
Hi,

this module works great, thanks.
But the delimiter variables should be named `separator` and `lineSeparator` relatively (with `a` instead of `e`). 😉

**Comment by jub3i** [comment]
Hi @jneuendorf sorry to take so long to reply! You are completely correct, now where is your pull request? :D

**Comment by jneuendorf** [comment]
There it is: https://github.com/jub3i/csv2sql-lite/pull/2 😉
